"""initial schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('base_url', sa.String(length=200), nullable=False),
    sa.Column('official', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('job', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_provider'), 'ingestion_runs', ['provider'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('instrument_type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=160), nullable=True),
    sa.Column('cik', sa.String(length=10), nullable=True),
    sa.Column('metadata_source', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', name='uq_instrument_symbol_exchange')
    )
    op.create_index(op.f('ix_instruments_cik'), 'instruments', ['cik'], unique=False)
    op.create_index('ix_instruments_name', 'instruments', ['name'], unique=False)
    op.create_table('macro_series',
    sa.Column('series_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('units', sa.String(length=80), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('assumed_lag_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('feature_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', 'feature_version', name='uq_model_version')
    )
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_cutoff', sa.Date(), nullable=False),
    sa.Column('n_obs', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('calibration', sa.JSON(), nullable=True),
    sa.Column('strategy', sa.JSON(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_reasons', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_instrument_id'), 'backtest_runs', ['instrument_id'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=12), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'ex_date', 'action_type')
    )
    op.create_table('derived_features',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('asof_date', sa.Date(), nullable=False),
    sa.Column('feature_version', sa.String(length=20), nullable=False),
    sa.Column('feature_values', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'asof_date', 'feature_version')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_cutoff', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('expected_return', sa.Float(), nullable=True),
    sa.Column('prob_up', sa.Float(), nullable=True),
    sa.Column('prob_down', sa.Float(), nullable=True),
    sa.Column('interval_low', sa.Float(), nullable=True),
    sa.Column('interval_high', sa.Float(), nullable=True),
    sa.Column('interval_level', sa.Float(), nullable=True),
    sa.Column('interval_method', sa.String(length=300), nullable=True),
    sa.Column('hist_vol_ann', sa.Float(), nullable=True),
    sa.Column('est_vol_ann', sa.Float(), nullable=True),
    sa.Column('feature_version', sa.String(length=20), nullable=False),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forecast_lookup', 'forecasts', ['instrument_id', 'horizon_days', 'created_at'], unique=False)
    op.create_index(op.f('ix_forecasts_instrument_id'), 'forecasts', ['instrument_id'], unique=False)
    op.create_table('fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(length=40), nullable=False),
    sa.Column('source_tag', sa.String(length=120), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_period', sa.String(length=4), nullable=True),
    sa.Column('form', sa.String(length=12), nullable=True),
    sa.Column('filed', sa.Date(), nullable=False),
    sa.Column('accession', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'concept', 'source_tag', 'period_start', 'period_end', 'accession', name='uq_fundamental_fact')
    )
    op.create_index('ix_fund_lookup', 'fundamentals', ['instrument_id', 'concept', 'period_end'], unique=False)
    op.create_table('macro_observations',
    sa.Column('series_id', sa.String(length=40), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('pit_quality', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['macro_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'observation_date', 'published_date')
    )
    op.create_table('prices',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('source_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'date', 'provider')
    )
    op.create_table('backtest_predictions',
    sa.Column('backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('asof_date', sa.Date(), nullable=False),
    sa.Column('prob_up', sa.Float(), nullable=False),
    sa.Column('baseline_prob_up', sa.Float(), nullable=False),
    sa.Column('pred_return', sa.Float(), nullable=False),
    sa.Column('baseline_return', sa.Float(), nullable=False),
    sa.Column('actual_return', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('backtest_run_id', 'asof_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backtest_predictions')
    op.drop_table('prices')
    op.drop_table('macro_observations')
    op.drop_index('ix_fund_lookup', table_name='fundamentals')
    op.drop_table('fundamentals')
    op.drop_index(op.f('ix_forecasts_instrument_id'), table_name='forecasts')
    op.drop_index('ix_forecast_lookup', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_table('derived_features')
    op.drop_table('corporate_actions')
    op.drop_index(op.f('ix_backtest_runs_instrument_id'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_table('model_versions')
    op.drop_table('macro_series')
    op.drop_index('ix_instruments_name', table_name='instruments')
    op.drop_index(op.f('ix_instruments_cik'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_ingestion_runs_provider'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_table('data_providers')
    # ### end Alembic commands ###
